//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2008.11.11 at 05:53:21 PM CST
//


package pedagogicalcontent;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CCDiodeExperimentResult complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CCDiodeExperimentResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="experimentType" type="{http://ilab.oauife.edu.ng/CCDiodes}ExperimentTypeEnum"/>
 *         &lt;element name="sampleClockPeriod" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="channel1Data" type="{http://ilab.oauife.edu.ng/CCDiodes}ListOfSamples"/>
 *         &lt;element name="channel2Data" type="{http://ilab.oauife.edu.ng/CCDiodes}ListOfSamples"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlRootElement(name="Result")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DsssExperimentResult", propOrder = {
    "experimentType",
    "sampleClockPeriod",
    "channel1Data",
    "channel2Data"
})
public class DsssExperimentResult {

    @XmlElement(required = true)

    protected int sampleClockPeriod;
    @XmlList
    @XmlElement(type = Double.class)
    protected List<Double> channel1Data;
    @XmlList
    @XmlElement(type = Double.class)
    protected List<Double> channel2Data;

    /**
     * Gets the value of the experimentType property.
     *
     * @return
     *     possible object is
     *     {@link ExperimentTypeEnum }
     *
     */


    /**
     * Gets the value of the sampleClockPeriod property.
     *
     */
    public int getSampleClockPeriod() {
        return sampleClockPeriod;
    }

    /**
     * Sets the value of the sampleClockPeriod property.
     *
     */
    public void setSampleClockPeriod(int value) {
        this.sampleClockPeriod = value;
    }

    /**
     * Gets the value of the channel1Data property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the channel1Data property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChannel1Data().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Double }
     *
     *
     */
    public List<Double> getChannel1Data() {
        if (channel1Data == null) {
            channel1Data = new ArrayList<Double>();
        }
        return this.channel1Data;
    }

    /**
     * Gets the value of the channel2Data property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the channel2Data property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChannel2Data().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Double }
     *
     *
     */
    public List<Double> getChannel2Data() {
        if (channel2Data == null) {
            channel2Data = new ArrayList<Double>();
        }
        return this.channel2Data;
    }

}
