//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2008.11.11 at 05:48:37 PM CST
//


package pedagogicalcontent;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CVEExperiment complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CVEExperiment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="experimentType" type="{http://ilab.oauife.edu.ng/CCDiodes}ExperimentTypeEnum"/>
 *         &lt;element name="signalAmplitude" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="signalFrequency" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="numberOfSignalCycles" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dcSupplyVoltage" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlRootElement(name="Experiment")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DssswExperiment", propOrder = {
    "analog",
    "digital"
    
    
})


public class DsssExperiment {

    @XmlElement(required = true)
    protected int analog;
    protected int digital;
    
       
    public int getAnalog() {
        return analog;
    }

    public void setAnalog(int value) {
        this.analog = value;
    }

   
   public int getDigital() {
        return digital;
    }

    public void setDigital(int value) {
        this.digital = value;
    }


}
