//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.17 at 01:23:30 PM GMT-12:00 
//


package pedagogicalcontent;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pedagogicalcontent package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Experiment_QNAME = new QName("http://ilab.oauife.edu.ng/CVE", "Experiment");
    private final static QName _Result_QNAME = new QName("http://ilab.oauife.edu.ng/CVE", "Result");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pedagogicalcontent
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CVEExperiment }
     * 
     */
    public DsssExperiment createCVEExperiment() {
        return new DsssExperiment();
    }

    /**
     * Create an instance of {@link CVEExperimentResult }
     * 
     */
    public DsssExperimentResult createCVEExperimentResult() {
        return new DsssExperimentResult();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CVEExperiment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ilab.oauife.edu.ng/CVE", name = "Experiment")
    public JAXBElement<DsssExperiment> createExperiment(DsssExperiment value) {
        return new JAXBElement<DsssExperiment>(_Experiment_QNAME, DsssExperiment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CVEExperimentResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ilab.oauife.edu.ng/CVE", name = "Result")
    public JAXBElement<DsssExperimentResult> createResult(DsssExperimentResult value) {
        return new JAXBElement<DsssExperimentResult>(_Result_QNAME, DsssExperimentResult.class, null, value);
    }

}
