//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.17 at 01:23:30 PM GMT-12:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ilab.oauife.edu.ng/CVE")
package pedagogicalcontent;
